import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "@/component/navigation";
import {
  ClerkProvider,

} from '@clerk/nextjs'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
<ClerkProvider>
<html lang="en">

<body
  className={`${geistSans.variable} ${geistMono.variable} min-h-screen antialiased`}
>
         <Navigation></Navigation> 
   
  {children}
  <footer className="p-5 text-center text-3xl  ">Blog Post End</footer>
</body>
</html>
</ClerkProvider>
  );
}
